version: '3.8'
services:
  dabble-mongodb:
    image: mongo:4.4.15
    # If you want to expose these ports outside your dev PC, remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:27017:27017"