@startumlparticipant User #FFFCEBparticipant Postman      #E8FDF5participant GitHub #CDECFFparticipant BE      #E8FDF5participant Mongo      #E8FDF5participant Firebase #CDECFFUser -> Postman: Obtain new access tokenPostman --> User: Show GH login pop-upUser -> GitHub: Log in at GHGitHub --> User: Option Authorize or DenyUser -> GitHub: AuthorizeGitHub --> Postman: Redirect, new Auth CodePostman -> GitHub: Auth Code, Client ID+SecretGitHub --> Postman: Access Token, Refresh Tokengroup Start Session    Postman -> BE: /api/auth/signin (authProvider, accessToken)    BE -> Firebase: GithubAuthProvider.credential(accessToken)    BE -> Firebase: getAuth(firebaseConfig)    BE -> Firebase: signInWithCredential(auth, cred)    Firebase --> BE: User    BE -> Mongo: Insert session (displayName, providerId, uid)endBE --> Postman: displayName, providerId, uidPostman --> User: displayName, providerId, uid@enduml