@startumlparticipant User #FFFCEBparticipant FE      #E8FDF5participant GitHub #CDECFFparticipant Firebase #CDECFFUser -> FE: Click sign-in buttonFE -> Firebase: firebaseui.auth.ui.AuthUI()FE -> Firebase: authUI.start(signInOptions)Firebase --> User: Show GH login pop-upUser -> GitHub: Log in at GHGitHub --> User: Option Authorize or DenyUser -> GitHub: AuthorizeGitHub --> Firebase: Redirect, new Auth CodeFirebase --> FE: displayName, providerId, uidFE --> User: Status@enduml