@startumlparticipant NewUser #FFFCEBparticipant FE      #E8FDF5participant Facebook #CDECFFparticipant BE      #E8FDF5NewUser -> FE: Sign-up with OAuthFE --> NewUser: Facebook Auth Code LinkNewUser -> Facebook: Log in at FacebookFacebook --> NewUser: Option Authorize or DenyNewUser -> Facebook: AuthorizeFacebook --> FE: Redirect, new Auth CodeFE -> Facebook: Auth Code, Client ID+SecretFacebook --> FE: Access Token, Refresh Tokengroup New Account Creation    FE -> BE: Access Token, Begin Registration    FE -> Facebook: Access Token    Facebook --> FE: Email    FE -> BE: Email    BE --> FE: Email, New UUID    FE --> NewUser: Show New Account UUID, Email    NewUser -> FE: Confirm Fields UUID, Email    FE -> BE: Finish RegistrationendBE --> FE: StatusFE --> NewUser: Status@enduml